---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ports:
    - name: backend-port
      port: {{ .Values.server_port }}
      targetPort: {{ .Values.server_port }}
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "{{ .Release.Name }}"
