[package]
name = "taxes-redux"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
nalgebra = "0.33.0"
itertools = "0.10"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
assert_approx_eq = "1.0"

