---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "{{ .Values.image }}"
          imagePullPolicy: Always
          name: "{{ .Release.Name }}"
          ports:
            - containerPort: {{ .Values.nginx_port }}
          resources:
            limits:
              cpu: "{{ .Values.cpu }}"
              memory: "{{ .Values.memory }}"
            requests:
              cpu: "{{ .Values.cpu }}"
              memory: "{{ .Values.memory }}"
          env:
            - name: NGINX_PORT
              value: "{{ .Values.nginx_port }}"
            - name: REACT_APP_BACKEND_HOST
              value: {{ .Values.domain }}
            - name: REACT_APP_BACKEND_PROTOCOL
              value: {{ .Values.protocol }}
